<?php declare(strict_types = 1);

/**
 * @file
 * Provides a location entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function migrate_source_mongo_theme(): array {
  return [
    'migrate_source_mongo_location' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for location templates.
 *
 * Default template: migrate-source-mongo-location.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the location information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_migrate_source_mongo_location(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function migrate_source_mongo_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish locations.
      $storage = \Drupal::entityTypeManager()->getStorage('migrate_source_mongo_location');
      $migrate_source_mongo_location_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($migrate_source_mongo_location_ids) as $migrate_source_mongo_location) {
        $migrate_source_mongo_location->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize locations.
      $storage = \Drupal::entityTypeManager()->getStorage('migrate_source_mongo_location');
      $migrate_source_mongo_location_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($migrate_source_mongo_location_ids) as $migrate_source_mongo_location) {
        $migrate_source_mongo_location->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function migrate_source_mongo_user_predelete(UserInterface $account): void {
  // Delete locations that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('migrate_source_mongo_location');
  $migrate_source_mongo_location_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($migrate_source_mongo_location_ids)
  );
}
